package com.example.epledger.util

import com.example.epledger.R

object IconAsset {
    val assets = arrayOf(
            R.drawable.u_ac_unit,
            R.drawable.u_access_alarm,
            R.drawable.u_access_time,
            R.drawable.u_accessibility_new,
            R.drawable.u_accessible,
            R.drawable.u_account_balance,
            R.drawable.u_account_balance_wallet,
            R.drawable.u_account_circle,
            R.drawable.u_ad_units,
            R.drawable.u_admin_panel_settings,
            R.drawable.u_agriculture,
            R.drawable.u_air,
            R.drawable.u_airline_seat_flat,
            R.drawable.u_airline_seat_recline_extra,
            R.drawable.u_airplane_ticket,
            R.drawable.u_airplanemode_active,
            R.drawable.u_airplay,
            R.drawable.u_airport_shuttle,
            R.drawable.u_apartment,
            R.drawable.u_architecture,
            R.drawable.u_archive,
            R.drawable.u_assignment,
            R.drawable.u_assignment_ind,
            R.drawable.u_assistant_photo,
            R.drawable.u_attach_file,
            R.drawable.u_attach_money,
            R.drawable.u_audiotrack,
            R.drawable.u_baby_changing_station,
            R.drawable.u_back_hand,
            R.drawable.u_backup,
            R.drawable.u_bedtime,
            R.drawable.u_bolt,
            R.drawable.u_book,
            R.drawable.u_bookmark,
            R.drawable.u_brush,
            R.drawable.u_bug_report,
            R.drawable.u_build,
            R.drawable.u_business,
            R.drawable.u_business_center,
            R.drawable.u_cake,
            R.drawable.u_camera_alt,
            R.drawable.u_chair,
            R.drawable.u_child_care,
            R.drawable.u_color_lens,
            R.drawable.u_directions_car,
            R.drawable.u_eco,
            R.drawable.u_elderly,
            R.drawable.u_email,
            R.drawable.u_emergency,
            R.drawable.u_emoji_emotions,
            R.drawable.u_emoji_events,
            R.drawable.u_family_restroom,
            R.drawable.u_fastfood,
            R.drawable.u_free_breakfast,
            R.drawable.u_grade,
            R.drawable.u_home,
            R.drawable.u_local_grocery_store,
            R.drawable.u_sports_basketball,
            R.drawable.u_sports_tennis,
            R.drawable.u_style,
            R.drawable.u_thumb_up_alt,
            R.drawable.u_translate,
            R.drawable.u_unarchive,
            R.drawable.ic_fab_500px,
            R.drawable.ic_fab_accessible_icon,
            R.drawable.ic_fab_accusoft,
            R.drawable.ic_fab_adn,
            R.drawable.ic_fab_adversal,
            R.drawable.ic_fab_affiliatetheme,
            R.drawable.ic_fab_algolia,
            R.drawable.ic_fab_amazon,
            R.drawable.ic_fab_amazon_pay,
            R.drawable.ic_fab_amilia,
            R.drawable.ic_fab_android,
            R.drawable.ic_fab_angellist,
            R.drawable.ic_fab_angrycreative,
            R.drawable.ic_fab_angular,
            R.drawable.ic_fab_app_store,
            R.drawable.ic_fab_app_store_ios,
            R.drawable.ic_fab_apper,
            R.drawable.ic_fab_apple,
            R.drawable.ic_fab_apple_pay,
            R.drawable.ic_fab_asymmetrik,
            R.drawable.ic_fab_audible,
            R.drawable.ic_fab_autoprefixer,
            R.drawable.ic_fab_avianex,
            R.drawable.ic_fab_aviato,
            R.drawable.ic_fab_aws,
            R.drawable.ic_fab_bandcamp,
            R.drawable.ic_fab_behance,
            R.drawable.ic_fab_behance_square,
            R.drawable.ic_fab_bimobject,
            R.drawable.ic_fab_bitbucket,
            R.drawable.ic_fab_bitcoin,
            R.drawable.ic_fab_bity,
            R.drawable.ic_fab_black_tie,
            R.drawable.ic_fab_blackberry,
            R.drawable.ic_fab_blogger,
            R.drawable.ic_fab_blogger_b,
            R.drawable.ic_fab_bluetooth,
            R.drawable.ic_fab_bluetooth_b,
            R.drawable.ic_fab_btc,
            R.drawable.ic_fab_buromobelexperte,
            R.drawable.ic_fab_buysellads,
            R.drawable.ic_fab_cc_amazon_pay,
            R.drawable.ic_fab_cc_amex,
            R.drawable.ic_fab_cc_apple_pay,
            R.drawable.ic_fab_cc_diners_club,
            R.drawable.ic_fab_cc_discover,
            R.drawable.ic_fab_cc_jcb,
            R.drawable.ic_fab_cc_mastercard,
            R.drawable.ic_fab_cc_paypal,
            R.drawable.ic_fab_cc_stripe,
            R.drawable.ic_fab_cc_visa,
            R.drawable.ic_fab_centercode,
            R.drawable.ic_fab_chrome,
            R.drawable.ic_fab_cloudscale,
            R.drawable.ic_fab_cloudsmith,
            R.drawable.ic_fab_cloudversify,
            R.drawable.ic_fab_codepen,
            R.drawable.ic_fab_codiepie,
            R.drawable.ic_fab_connectdevelop,
            R.drawable.ic_fab_contao,
            R.drawable.ic_fab_cpanel,
            R.drawable.ic_fab_creative_commons,
            R.drawable.ic_fab_css3,
            R.drawable.ic_fab_css3_alt,
            R.drawable.ic_fab_cuttlefish,
            R.drawable.ic_fab_d_and_d,
            R.drawable.ic_fab_dashcube,
            R.drawable.ic_fab_delicious,
            R.drawable.ic_fab_deploydog,
            R.drawable.ic_fab_deskpro,
            R.drawable.ic_fab_deviantart,
            R.drawable.ic_fab_digg,
            R.drawable.ic_fab_digital_ocean,
            R.drawable.ic_fab_discord,
            R.drawable.ic_fab_discourse,
            R.drawable.ic_fab_dochub,
            R.drawable.ic_fab_docker,
            R.drawable.ic_fab_draft2digital,
            R.drawable.ic_fab_dribbble,
            R.drawable.ic_fab_dribbble_square,
            R.drawable.ic_fab_dropbox,
            R.drawable.ic_fab_drupal,
            R.drawable.ic_fab_dyalog,
            R.drawable.ic_fab_earlybirds,
            R.drawable.ic_fab_edge,
            R.drawable.ic_fab_elementor,
            R.drawable.ic_fab_ember,
            R.drawable.ic_fab_empire,
            R.drawable.ic_fab_envira,
            R.drawable.ic_fab_erlang,
            R.drawable.ic_fab_ethereum,
            R.drawable.ic_fab_etsy,
            R.drawable.ic_fab_expeditedssl,
            R.drawable.ic_fab_facebook,
            R.drawable.ic_fab_facebook_f,
            R.drawable.ic_fab_facebook_messenger,
            R.drawable.ic_fab_facebook_square,
            R.drawable.ic_fab_firefox,
            R.drawable.ic_fab_first_order,
            R.drawable.ic_fab_firstdraft,
            R.drawable.ic_fab_flickr,
            R.drawable.ic_fab_fly,
            R.drawable.ic_fab_font_awesome,
            R.drawable.ic_fab_font_awesome_alt,
            R.drawable.ic_fab_font_awesome_flag,
            R.drawable.ic_fab_fonticons,
            R.drawable.ic_fab_fonticons_fi,
            R.drawable.ic_fab_fort_awesome,
            R.drawable.ic_fab_fort_awesome_alt,
            R.drawable.ic_fab_forumbee,
            R.drawable.ic_fab_foursquare,
            R.drawable.ic_fab_free_code_camp,
            R.drawable.ic_fab_freebsd,
            R.drawable.ic_fab_get_pocket,
            R.drawable.ic_fab_gg,
            R.drawable.ic_fab_gg_circle,
            R.drawable.ic_fab_git,
            R.drawable.ic_fab_git_square,
            R.drawable.ic_fab_github,
            R.drawable.ic_fab_github_alt,
            R.drawable.ic_fab_github_square,
            R.drawable.ic_fab_gitkraken,
            R.drawable.ic_fab_gitlab,
            R.drawable.ic_fab_gitter,
            R.drawable.ic_fab_glide,
            R.drawable.ic_fab_glide_g,
            R.drawable.ic_fab_gofore,
            R.drawable.ic_fab_goodreads,
            R.drawable.ic_fab_goodreads_g,
            R.drawable.ic_fab_google,
            R.drawable.ic_fab_google_drive,
            R.drawable.ic_fab_google_play,
            R.drawable.ic_fab_google_plus,
            R.drawable.ic_fab_google_plus_g,
            R.drawable.ic_fab_google_plus_square,
            R.drawable.ic_fab_google_wallet,
            R.drawable.ic_fab_gratipay,
            R.drawable.ic_fab_grav,
            R.drawable.ic_fab_gripfire,
            R.drawable.ic_fab_grunt,
            R.drawable.ic_fab_gulp,
            R.drawable.ic_fab_hacker_news,
            R.drawable.ic_fab_hacker_news_square,
            R.drawable.ic_fab_hire_a_helper,
            R.drawable.ic_fab_hooli,
            R.drawable.ic_fab_hotjar,
            R.drawable.ic_fab_houzz,
            R.drawable.ic_fab_html5,
            R.drawable.ic_fab_hubspot,
            R.drawable.ic_fab_imdb,
            R.drawable.ic_fab_instagram,
            R.drawable.ic_fab_internet_explorer,
            R.drawable.ic_fab_ioxhost,
            R.drawable.ic_fab_itunes,
            R.drawable.ic_fab_itunes_note,
            R.drawable.ic_fab_jenkins,
            R.drawable.ic_fab_joget,
            R.drawable.ic_fab_joomla,
            R.drawable.ic_fab_js,
            R.drawable.ic_fab_js_square,
            R.drawable.ic_fab_jsfiddle,
            R.drawable.ic_fab_keycdn,
            R.drawable.ic_fab_kickstarter,
            R.drawable.ic_fab_kickstarter_k,
            R.drawable.ic_fab_korvue,
            R.drawable.ic_fab_laravel,
            R.drawable.ic_fab_lastfm,
            R.drawable.ic_fab_lastfm_square,
            R.drawable.ic_fab_leanpub,
            R.drawable.ic_fab_less,
            R.drawable.ic_fab_line,
            R.drawable.ic_fab_linkedin,
            R.drawable.ic_fab_linkedin_in,
            R.drawable.ic_fab_linode,
            R.drawable.ic_fab_linux,
            R.drawable.ic_fab_lyft,
            R.drawable.ic_fab_magento,
            R.drawable.ic_fab_maxcdn,
            R.drawable.ic_fab_medapps,
            R.drawable.ic_fab_medium,
            R.drawable.ic_fab_medium_m,
            R.drawable.ic_fab_medrt,
            R.drawable.ic_fab_meetup,
            R.drawable.ic_fab_microsoft,
            R.drawable.ic_fab_mix,
            R.drawable.ic_fab_mixcloud,
            R.drawable.ic_fab_mizuni,
            R.drawable.ic_fab_modx,
            R.drawable.ic_fab_monero,
            R.drawable.ic_fab_napster,
            R.drawable.ic_fab_nintendo_switch,
            R.drawable.ic_fab_node,
            R.drawable.ic_fab_node_js,
            R.drawable.ic_fab_npm,
            R.drawable.ic_fab_ns8,
            R.drawable.ic_fab_nutritionix,
            R.drawable.ic_fab_odnoklassniki,
            R.drawable.ic_fab_odnoklassniki_square,
            R.drawable.ic_fab_opencart,
            R.drawable.ic_fab_openid,
            R.drawable.ic_fab_opera,
            R.drawable.ic_fab_optin_monster,
            R.drawable.ic_fab_osi,
            R.drawable.ic_fab_page4,
            R.drawable.ic_fab_pagelines,
            R.drawable.ic_fab_palfed,
            R.drawable.ic_fab_patreon,
            R.drawable.ic_fab_paypal,
            R.drawable.ic_fab_periscope,
            R.drawable.ic_fab_phabricator,
            R.drawable.ic_fab_phoenix_framework,
            R.drawable.ic_fab_pied_piper,
            R.drawable.ic_fab_pied_piper_alt,
            R.drawable.ic_fab_pied_piper_pp,
            R.drawable.ic_fab_pinterest,
            R.drawable.ic_fab_pinterest_p,
            R.drawable.ic_fab_pinterest_square,
            R.drawable.ic_fab_playstation,
            R.drawable.ic_fab_product_hunt,
            R.drawable.ic_fab_pushed,
            R.drawable.ic_fab_python,
            R.drawable.ic_fab_qq,
            R.drawable.ic_fab_quora,
            R.drawable.ic_fab_ravelry,
            R.drawable.ic_fab_react,
            R.drawable.ic_fab_rebel,
            R.drawable.ic_fab_red_river,
            R.drawable.ic_fab_reddit,
            R.drawable.ic_fab_reddit_alien,
            R.drawable.ic_fab_reddit_square,
            R.drawable.ic_fab_rendact,
            R.drawable.ic_fab_renren,
            R.drawable.ic_fab_replyd,
            R.drawable.ic_fab_resolving,
            R.drawable.ic_fab_rocketchat,
            R.drawable.ic_fab_rockrms,
            R.drawable.ic_fab_safari,
            R.drawable.ic_fab_sass,
            R.drawable.ic_fab_schlix,
            R.drawable.ic_fab_scribd,
            R.drawable.ic_fab_searchengin,
            R.drawable.ic_fab_sellcast,
            R.drawable.ic_fab_sellsy,
            R.drawable.ic_fab_servicestack,
            R.drawable.ic_fab_shirtsinbulk,
            R.drawable.ic_fab_simplybuilt,
            R.drawable.ic_fab_sistrix,
            R.drawable.ic_fab_skyatlas,
            R.drawable.ic_fab_skype,
            R.drawable.ic_fab_slack,
            R.drawable.ic_fab_slack_hash,
            R.drawable.ic_fab_slideshare,
            R.drawable.ic_fab_snapchat,
            R.drawable.ic_fab_snapchat_ghost,
            R.drawable.ic_fab_snapchat_square,
            R.drawable.ic_fab_soundcloud,
            R.drawable.ic_fab_speakap,
            R.drawable.ic_fab_spotify,
            R.drawable.ic_fab_stack_exchange,
            R.drawable.ic_fab_stack_overflow,
            R.drawable.ic_fab_staylinked,
            R.drawable.ic_fab_steam,
            R.drawable.ic_fab_steam_square,
            R.drawable.ic_fab_steam_symbol,
            R.drawable.ic_fab_sticker_mule,
            R.drawable.ic_fab_strava,
            R.drawable.ic_fab_stripe,
            R.drawable.ic_fab_stripe_s,
            R.drawable.ic_fab_studiovinari,
            R.drawable.ic_fab_stumbleupon,
            R.drawable.ic_fab_stumbleupon_circle,
            R.drawable.ic_fab_superpowers,
            R.drawable.ic_fab_supple,
            R.drawable.ic_fab_telegram,
            R.drawable.ic_fab_telegram_plane,
            R.drawable.ic_fab_tencent_weibo,
            R.drawable.ic_fab_themeisle,
            R.drawable.ic_fab_trello,
            R.drawable.ic_fab_tripadvisor,
            R.drawable.ic_fab_tumblr,
            R.drawable.ic_fab_tumblr_square,
            R.drawable.ic_fab_twitch,
            R.drawable.ic_fab_twitter,
            R.drawable.ic_fab_twitter_square,
            R.drawable.ic_fab_typo3,
            R.drawable.ic_fab_uber,
            R.drawable.ic_fab_uikit,
            R.drawable.ic_fab_uniregistry,
            R.drawable.ic_fab_untappd,
            R.drawable.ic_fab_usb,
            R.drawable.ic_fab_ussunnah,
            R.drawable.ic_fab_vaadin,
            R.drawable.ic_fab_viacoin,
            R.drawable.ic_fab_viadeo,
            R.drawable.ic_fab_viadeo_square,
            R.drawable.ic_fab_viber,
            R.drawable.ic_fab_vimeo,
            R.drawable.ic_fab_vimeo_square,
            R.drawable.ic_fab_vimeo_v,
            R.drawable.ic_fab_vine,
            R.drawable.ic_fab_vk,
            R.drawable.ic_fab_vnv,
            R.drawable.ic_fab_vuejs,
            R.drawable.ic_fab_weibo,
            R.drawable.ic_fab_weixin,
            R.drawable.ic_fab_whatsapp,
            R.drawable.ic_fab_whatsapp_square,
            R.drawable.ic_fab_whmcs,
            R.drawable.ic_fab_wikipedia_w,
            R.drawable.ic_fab_windows,
            R.drawable.ic_fab_wordpress,
            R.drawable.ic_fab_wordpress_simple,
            R.drawable.ic_fab_wpbeginner,
            R.drawable.ic_fab_wpexplorer,
            R.drawable.ic_fab_wpforms,
            R.drawable.ic_fab_xbox,
            R.drawable.ic_fab_xing,
            R.drawable.ic_fab_xing_square,
            R.drawable.ic_fab_y_combinator,
            R.drawable.ic_fab_yahoo,
            R.drawable.ic_fab_yandex,
            R.drawable.ic_fab_yandex_international,
            R.drawable.ic_fab_yelp,
            R.drawable.ic_fab_yoast,
            R.drawable.ic_fab_youtube,
            R.drawable.ic_fab_youtube_square,
//            R.drawable.ic_far_address_book,
//            R.drawable.ic_far_address_card,
//            R.drawable.ic_far_arrow_alt_circle_down,
//            R.drawable.ic_far_arrow_alt_circle_left,
//            R.drawable.ic_far_arrow_alt_circle_right,
//            R.drawable.ic_far_arrow_alt_circle_up,
//            R.drawable.ic_far_bell,
//            R.drawable.ic_far_bell_slash,
//            R.drawable.ic_far_bookmark,
//            R.drawable.ic_far_building,
//            R.drawable.ic_far_calendar,
//            R.drawable.ic_far_calendar_alt,
//            R.drawable.ic_far_calendar_check,
//            R.drawable.ic_far_calendar_minus,
//            R.drawable.ic_far_calendar_plus,
//            R.drawable.ic_far_calendar_times,
//            R.drawable.ic_far_caret_square_down,
//            R.drawable.ic_far_caret_square_left,
//            R.drawable.ic_far_caret_square_right,
//            R.drawable.ic_far_caret_square_up,
//            R.drawable.ic_far_chart_bar,
//            R.drawable.ic_far_check_circle,
//            R.drawable.ic_far_check_square,
//            R.drawable.ic_far_circle,
//            R.drawable.ic_far_clipboard,
//            R.drawable.ic_far_clock,
//            R.drawable.ic_far_clone,
//            R.drawable.ic_far_closed_captioning,
//            R.drawable.ic_far_comment,
//            R.drawable.ic_far_comment_alt,
//            R.drawable.ic_far_comments,
//            R.drawable.ic_far_compass,
//            R.drawable.ic_far_copy,
//            R.drawable.ic_far_copyright,
//            R.drawable.ic_far_credit_card,
//            R.drawable.ic_far_dot_circle,
//            R.drawable.ic_far_edit,
//            R.drawable.ic_far_envelope,
//            R.drawable.ic_far_envelope_open,
//            R.drawable.ic_far_eye_slash,
//            R.drawable.ic_far_file,
//            R.drawable.ic_far_file_alt,
//            R.drawable.ic_far_file_archive,
//            R.drawable.ic_far_file_audio,
//            R.drawable.ic_far_file_code,
//            R.drawable.ic_far_file_excel,
//            R.drawable.ic_far_file_image,
//            R.drawable.ic_far_file_pdf,
//            R.drawable.ic_far_file_powerpoint,
//            R.drawable.ic_far_file_video,
//            R.drawable.ic_far_file_word,
//            R.drawable.ic_far_flag,
//            R.drawable.ic_far_folder,
//            R.drawable.ic_far_folder_open,
//            R.drawable.ic_far_frown,
//            R.drawable.ic_far_futbol,
//            R.drawable.ic_far_gem,
//            R.drawable.ic_far_hand_lizard,
//            R.drawable.ic_far_hand_paper,
//            R.drawable.ic_far_hand_peace,
//            R.drawable.ic_far_hand_point_down,
//            R.drawable.ic_far_hand_point_left,
//            R.drawable.ic_far_hand_point_right,
//            R.drawable.ic_far_hand_point_up,
//            R.drawable.ic_far_hand_pointer,
//            R.drawable.ic_far_hand_rock,
//            R.drawable.ic_far_hand_scissors,
//            R.drawable.ic_far_hand_spock,
//            R.drawable.ic_far_handshake,
//            R.drawable.ic_far_hdd,
//            R.drawable.ic_far_heart,
//            R.drawable.ic_far_hospital,
//            R.drawable.ic_far_hourglass,
//            R.drawable.ic_far_id_badge,
//            R.drawable.ic_far_id_card,
//            R.drawable.ic_far_image,
//            R.drawable.ic_far_images,
//            R.drawable.ic_far_keyboard,
//            R.drawable.ic_far_lemon,
//            R.drawable.ic_far_life_ring,
//            R.drawable.ic_far_lightbulb,
//            R.drawable.ic_far_list_alt,
//            R.drawable.ic_far_map,
//            R.drawable.ic_far_meh,
//            R.drawable.ic_far_minus_square,
//            R.drawable.ic_far_money_bill_alt,
//            R.drawable.ic_far_moon,
//            R.drawable.ic_far_newspaper,
//            R.drawable.ic_far_object_group,
//            R.drawable.ic_far_object_ungroup,
//            R.drawable.ic_far_paper_plane,
//            R.drawable.ic_far_pause_circle,
//            R.drawable.ic_far_play_circle,
//            R.drawable.ic_far_plus_square,
//            R.drawable.ic_far_question_circle,
//            R.drawable.ic_far_registered,
//            R.drawable.ic_far_save,
//            R.drawable.ic_far_share_square,
//            R.drawable.ic_far_smile,
//            R.drawable.ic_far_snowflake,
//            R.drawable.ic_far_square,
//            R.drawable.ic_far_star,
//            R.drawable.ic_far_star_half,
//            R.drawable.ic_far_sticky_note,
//            R.drawable.ic_far_stop_circle,
//            R.drawable.ic_far_sun,
//            R.drawable.ic_far_thumbs_down,
//            R.drawable.ic_far_thumbs_up,
//            R.drawable.ic_far_times_circle,
//            R.drawable.ic_far_trash_alt,
//            R.drawable.ic_far_user,
//            R.drawable.ic_far_user_circle,
            R.drawable.ic_far_window_close,
            R.drawable.ic_far_window_maximize,
            R.drawable.ic_far_window_minimize,
            R.drawable.ic_far_window_restore,
            R.drawable.ic_fas_address_book,
            R.drawable.ic_fas_address_card,
            R.drawable.ic_fas_adjust,
            R.drawable.ic_fas_align_center,
            R.drawable.ic_fas_align_justify,
            R.drawable.ic_fas_align_left,
            R.drawable.ic_fas_align_right,
            R.drawable.ic_fas_ambulance,
            R.drawable.ic_fas_american_sign_language_interpreting,
            R.drawable.ic_fas_anchor,
            R.drawable.ic_fas_angle_double_down,
            R.drawable.ic_fas_angle_double_left,
            R.drawable.ic_fas_angle_double_right,
            R.drawable.ic_fas_angle_double_up,
            R.drawable.ic_fas_angle_down,
            R.drawable.ic_fas_angle_left,
            R.drawable.ic_fas_angle_right,
            R.drawable.ic_fas_angle_up,
            R.drawable.ic_fas_archive,
            R.drawable.ic_fas_arrow_alt_circle_down,
            R.drawable.ic_fas_arrow_alt_circle_left,
            R.drawable.ic_fas_arrow_alt_circle_right,
            R.drawable.ic_fas_arrow_alt_circle_up,
            R.drawable.ic_fas_arrow_circle_down,
            R.drawable.ic_fas_arrow_circle_left,
            R.drawable.ic_fas_arrow_circle_right,
            R.drawable.ic_fas_arrow_circle_up,
            R.drawable.ic_fas_arrow_down,
            R.drawable.ic_fas_arrow_left,
            R.drawable.ic_fas_arrow_right,
            R.drawable.ic_fas_arrow_up,
            R.drawable.ic_fas_arrows_alt,
            R.drawable.ic_fas_arrows_alt_h,
            R.drawable.ic_fas_arrows_alt_v,
            R.drawable.ic_fas_assistive_listening_systems,
            R.drawable.ic_fas_asterisk,
            R.drawable.ic_fas_at,
            R.drawable.ic_fas_audio_description,
            R.drawable.ic_fas_backward,
            R.drawable.ic_fas_balance_scale,
            R.drawable.ic_fas_ban,
            R.drawable.ic_fas_barcode,
            R.drawable.ic_fas_bars,
            R.drawable.ic_fas_bath,
            R.drawable.ic_fas_battery_empty,
            R.drawable.ic_fas_battery_full,
            R.drawable.ic_fas_battery_half,
            R.drawable.ic_fas_battery_quarter,
            R.drawable.ic_fas_battery_three_quarters,
            R.drawable.ic_fas_bed,
            R.drawable.ic_fas_beer,
            R.drawable.ic_fas_bell,
            R.drawable.ic_fas_bell_slash,
            R.drawable.ic_fas_bicycle,
            R.drawable.ic_fas_binoculars,
            R.drawable.ic_fas_birthday_cake,
            R.drawable.ic_fas_blind,
            R.drawable.ic_fas_bold,
            R.drawable.ic_fas_bolt,
            R.drawable.ic_fas_bomb,
            R.drawable.ic_fas_book,
            R.drawable.ic_fas_bookmark,
            R.drawable.ic_fas_braille,
            R.drawable.ic_fas_briefcase,
            R.drawable.ic_fas_bug,
            R.drawable.ic_fas_building,
            R.drawable.ic_fas_bullhorn,
            R.drawable.ic_fas_bullseye,
            R.drawable.ic_fas_bus,
            R.drawable.ic_fas_calculator,
            R.drawable.ic_fas_calendar,
            R.drawable.ic_fas_calendar_alt,
            R.drawable.ic_fas_calendar_check,
            R.drawable.ic_fas_calendar_minus,
            R.drawable.ic_fas_calendar_plus,
            R.drawable.ic_fas_calendar_times,
            R.drawable.ic_fas_camera,
            R.drawable.ic_fas_camera_retro,
            R.drawable.ic_fas_car,
            R.drawable.ic_fas_caret_down,
            R.drawable.ic_fas_caret_left,
            R.drawable.ic_fas_caret_right,
            R.drawable.ic_fas_caret_square_down,
            R.drawable.ic_fas_caret_square_left,
            R.drawable.ic_fas_caret_square_right,
            R.drawable.ic_fas_caret_square_up,
            R.drawable.ic_fas_caret_up,
            R.drawable.ic_fas_cart_arrow_down,
            R.drawable.ic_fas_cart_plus,
            R.drawable.ic_fas_certificate,
            R.drawable.ic_fas_chart_area,
            R.drawable.ic_fas_chart_bar,
            R.drawable.ic_fas_chart_line,
            R.drawable.ic_fas_chart_pie,
            R.drawable.ic_fas_check,
            R.drawable.ic_fas_check_circle,
            R.drawable.ic_fas_check_square,
            R.drawable.ic_fas_chevron_circle_down,
            R.drawable.ic_fas_chevron_circle_left,
            R.drawable.ic_fas_chevron_circle_right,
            R.drawable.ic_fas_chevron_circle_up,
            R.drawable.ic_fas_chevron_down,
            R.drawable.ic_fas_chevron_left,
            R.drawable.ic_fas_chevron_right,
            R.drawable.ic_fas_chevron_up,
            R.drawable.ic_fas_child,
            R.drawable.ic_fas_circle,
            R.drawable.ic_fas_circle_notch,
            R.drawable.ic_fas_clipboard,
            R.drawable.ic_fas_clock,
            R.drawable.ic_fas_clone,
            R.drawable.ic_fas_closed_captioning,
            R.drawable.ic_fas_cloud,
            R.drawable.ic_fas_cloud_download_alt,
            R.drawable.ic_fas_cloud_upload_alt,
            R.drawable.ic_fas_code,
            R.drawable.ic_fas_code_branch,
            R.drawable.ic_fas_coffee,
            R.drawable.ic_fas_cog,
            R.drawable.ic_fas_cogs,
            R.drawable.ic_fas_columns,
            R.drawable.ic_fas_comment,
            R.drawable.ic_fas_comment_alt,
            R.drawable.ic_fas_comments,
            R.drawable.ic_fas_compass,
            R.drawable.ic_fas_compress,
            R.drawable.ic_fas_copy,
            R.drawable.ic_fas_copyright,
            R.drawable.ic_fas_credit_card,
            R.drawable.ic_fas_crop,
            R.drawable.ic_fas_crosshairs,
            R.drawable.ic_fas_cube,
            R.drawable.ic_fas_cubes,
            R.drawable.ic_fas_cut,
            R.drawable.ic_fas_database,
            R.drawable.ic_fas_deaf,
            R.drawable.ic_fas_desktop,
            R.drawable.ic_fas_dollar_sign,
            R.drawable.ic_fas_dot_circle,
            R.drawable.ic_fas_download,
            R.drawable.ic_fas_edit,
            R.drawable.ic_fas_eject,
            R.drawable.ic_fas_ellipsis_h,
            R.drawable.ic_fas_ellipsis_v,
            R.drawable.ic_fas_envelope,
            R.drawable.ic_fas_envelope_open,
            R.drawable.ic_fas_envelope_square,
            R.drawable.ic_fas_eraser,
            R.drawable.ic_fas_euro_sign,
            R.drawable.ic_fas_exchange_alt,
            R.drawable.ic_fas_exclamation,
            R.drawable.ic_fas_exclamation_circle,
            R.drawable.ic_fas_exclamation_triangle,
            R.drawable.ic_fas_expand,
            R.drawable.ic_fas_expand_arrows_alt,
            R.drawable.ic_fas_external_link_alt,
            R.drawable.ic_fas_external_link_square_alt,
            R.drawable.ic_fas_eye,
            R.drawable.ic_fas_eye_dropper,
            R.drawable.ic_fas_eye_slash,
            R.drawable.ic_fas_fast_backward,
            R.drawable.ic_fas_fast_forward,
            R.drawable.ic_fas_fax,
            R.drawable.ic_fas_female,
            R.drawable.ic_fas_fighter_jet,
            R.drawable.ic_fas_file,
            R.drawable.ic_fas_file_alt,
            R.drawable.ic_fas_file_archive,
            R.drawable.ic_fas_file_audio,
            R.drawable.ic_fas_file_code,
            R.drawable.ic_fas_file_excel,
            R.drawable.ic_fas_file_image,
            R.drawable.ic_fas_file_pdf,
            R.drawable.ic_fas_file_powerpoint,
            R.drawable.ic_fas_file_video,
            R.drawable.ic_fas_file_word,
            R.drawable.ic_fas_film,
            R.drawable.ic_fas_filter,
            R.drawable.ic_fas_fire,
            R.drawable.ic_fas_fire_extinguisher,
            R.drawable.ic_fas_flag,
            R.drawable.ic_fas_flag_checkered,
            R.drawable.ic_fas_flask,
            R.drawable.ic_fas_folder,
            R.drawable.ic_fas_folder_open,
            R.drawable.ic_fas_font,
            R.drawable.ic_fas_forward,
            R.drawable.ic_fas_frown,
            R.drawable.ic_fas_futbol,
            R.drawable.ic_fas_gamepad,
            R.drawable.ic_fas_gavel,
            R.drawable.ic_fas_gem,
            R.drawable.ic_fas_genderless,
            R.drawable.ic_fas_gift,
            R.drawable.ic_fas_glass_martini,
            R.drawable.ic_fas_globe,
            R.drawable.ic_fas_graduation_cap,
            R.drawable.ic_fas_h_square,
            R.drawable.ic_fas_hand_lizard,
            R.drawable.ic_fas_hand_paper,
            R.drawable.ic_fas_hand_peace,
            R.drawable.ic_fas_hand_point_down,
            R.drawable.ic_fas_hand_point_left,
            R.drawable.ic_fas_hand_point_right,
            R.drawable.ic_fas_hand_point_up,
            R.drawable.ic_fas_hand_pointer,
            R.drawable.ic_fas_hand_rock,
            R.drawable.ic_fas_hand_scissors,
            R.drawable.ic_fas_hand_spock,
            R.drawable.ic_fas_handshake,
            R.drawable.ic_fas_hashtag,
            R.drawable.ic_fas_hdd,
            R.drawable.ic_fas_heading,
            R.drawable.ic_fas_headphones,
            R.drawable.ic_fas_heart,
            R.drawable.ic_fas_heartbeat,
            R.drawable.ic_fas_history,
            R.drawable.ic_fas_home,
            R.drawable.ic_fas_hospital,
            R.drawable.ic_fas_hourglass,
            R.drawable.ic_fas_hourglass_end,
            R.drawable.ic_fas_hourglass_half,
            R.drawable.ic_fas_hourglass_start,
            R.drawable.ic_fas_i_cursor,
            R.drawable.ic_fas_id_badge,
            R.drawable.ic_fas_id_card,
            R.drawable.ic_fas_image,
            R.drawable.ic_fas_images,
            R.drawable.ic_fas_inbox,
            R.drawable.ic_fas_indent,
            R.drawable.ic_fas_industry,
            R.drawable.ic_fas_info,
            R.drawable.ic_fas_info_circle,
            R.drawable.ic_fas_italic,
            R.drawable.ic_fas_key,
            R.drawable.ic_fas_keyboard,
            R.drawable.ic_fas_language,
            R.drawable.ic_fas_laptop,
            R.drawable.ic_fas_leaf,
            R.drawable.ic_fas_lemon,
            R.drawable.ic_fas_level_down_alt,
            R.drawable.ic_fas_level_up_alt,
            R.drawable.ic_fas_life_ring,
            R.drawable.ic_fas_lightbulb,
            R.drawable.ic_fas_link,
            R.drawable.ic_fas_lira_sign,
            R.drawable.ic_fas_list,
            R.drawable.ic_fas_list_alt,
            R.drawable.ic_fas_list_ol,
            R.drawable.ic_fas_list_ul,
            R.drawable.ic_fas_location_arrow,
            R.drawable.ic_fas_lock,
            R.drawable.ic_fas_lock_open,
            R.drawable.ic_fas_long_arrow_alt_down,
            R.drawable.ic_fas_long_arrow_alt_left,
            R.drawable.ic_fas_long_arrow_alt_right,
            R.drawable.ic_fas_long_arrow_alt_up,
            R.drawable.ic_fas_low_vision,
            R.drawable.ic_fas_magic,
            R.drawable.ic_fas_magnet,
            R.drawable.ic_fas_male,
            R.drawable.ic_fas_map,
            R.drawable.ic_fas_map_marker,
            R.drawable.ic_fas_map_marker_alt,
            R.drawable.ic_fas_map_pin,
            R.drawable.ic_fas_map_signs,
            R.drawable.ic_fas_mars,
            R.drawable.ic_fas_mars_double,
            R.drawable.ic_fas_mars_stroke,
            R.drawable.ic_fas_mars_stroke_h,
            R.drawable.ic_fas_mars_stroke_v,
            R.drawable.ic_fas_medkit,
            R.drawable.ic_fas_meh,
            R.drawable.ic_fas_mercury,
            R.drawable.ic_fas_microchip,
            R.drawable.ic_fas_microphone,
            R.drawable.ic_fas_microphone_slash,
            R.drawable.ic_fas_minus,
            R.drawable.ic_fas_minus_circle,
            R.drawable.ic_fas_minus_square,
            R.drawable.ic_fas_mobile,
            R.drawable.ic_fas_mobile_alt,
            R.drawable.ic_fas_money_bill_alt,
            R.drawable.ic_fas_moon,
            R.drawable.ic_fas_motorcycle,
            R.drawable.ic_fas_mouse_pointer,
            R.drawable.ic_fas_music,
            R.drawable.ic_fas_neuter,
            R.drawable.ic_fas_newspaper,
            R.drawable.ic_fas_object_group,
            R.drawable.ic_fas_object_ungroup,
            R.drawable.ic_fas_outdent,
            R.drawable.ic_fas_paint_brush,
            R.drawable.ic_fas_paper_plane,
            R.drawable.ic_fas_paperclip,
            R.drawable.ic_fas_paragraph,
            R.drawable.ic_fas_paste,
            R.drawable.ic_fas_pause,
            R.drawable.ic_fas_pause_circle,
            R.drawable.ic_fas_paw,
            R.drawable.ic_fas_pen_square,
            R.drawable.ic_fas_pencil_alt,
            R.drawable.ic_fas_percent,
            R.drawable.ic_fas_phone,
            R.drawable.ic_fas_phone_square,
            R.drawable.ic_fas_phone_volume,
            R.drawable.ic_fas_plane,
            R.drawable.ic_fas_play,
            R.drawable.ic_fas_play_circle,
            R.drawable.ic_fas_plug,
            R.drawable.ic_fas_plus,
            R.drawable.ic_fas_plus_circle,
            R.drawable.ic_fas_plus_square,
            R.drawable.ic_fas_podcast,
            R.drawable.ic_fas_pound_sign,
            R.drawable.ic_fas_power_off,
            R.drawable.ic_fas_print,
            R.drawable.ic_fas_puzzle_piece,
            R.drawable.ic_fas_qrcode,
            R.drawable.ic_fas_question,
            R.drawable.ic_fas_question_circle,
            R.drawable.ic_fas_quote_left,
            R.drawable.ic_fas_quote_right,
            R.drawable.ic_fas_random,
            R.drawable.ic_fas_recycle,
            R.drawable.ic_fas_redo,
            R.drawable.ic_fas_redo_alt,
            R.drawable.ic_fas_registered,
            R.drawable.ic_fas_reply,
            R.drawable.ic_fas_reply_all,
            R.drawable.ic_fas_retweet,
            R.drawable.ic_fas_road,
            R.drawable.ic_fas_rocket,
            R.drawable.ic_fas_rss,
            R.drawable.ic_fas_rss_square,
            R.drawable.ic_fas_ruble_sign,
            R.drawable.ic_fas_rupee_sign,
            R.drawable.ic_fas_save,
            R.drawable.ic_fas_search,
            R.drawable.ic_fas_search_minus,
            R.drawable.ic_fas_search_plus,
            R.drawable.ic_fas_server,
            R.drawable.ic_fas_share,
            R.drawable.ic_fas_share_alt,
            R.drawable.ic_fas_share_alt_square,
            R.drawable.ic_fas_share_square,
            R.drawable.ic_fas_shekel_sign,
            R.drawable.ic_fas_shield_alt,
            R.drawable.ic_fas_ship,
            R.drawable.ic_fas_shopping_bag,
            R.drawable.ic_fas_shopping_basket,
            R.drawable.ic_fas_shopping_cart,
            R.drawable.ic_fas_shower,
            R.drawable.ic_fas_sign_in_alt,
            R.drawable.ic_fas_sign_language,
            R.drawable.ic_fas_sign_out_alt,
            R.drawable.ic_fas_signal,
            R.drawable.ic_fas_sitemap,
            R.drawable.ic_fas_sliders_h,
            R.drawable.ic_fas_smile,
            R.drawable.ic_fas_snowflake,
            R.drawable.ic_fas_sort,
            R.drawable.ic_fas_sort_alpha_down,
            R.drawable.ic_fas_sort_alpha_up,
            R.drawable.ic_fas_sort_amount_down,
            R.drawable.ic_fas_sort_amount_up,
            R.drawable.ic_fas_sort_down,
            R.drawable.ic_fas_sort_numeric_down,
            R.drawable.ic_fas_sort_numeric_up,
            R.drawable.ic_fas_sort_up,
            R.drawable.ic_fas_space_shuttle,
            R.drawable.ic_fas_spinner,
            R.drawable.ic_fas_square,
            R.drawable.ic_fas_star,
            R.drawable.ic_fas_star_half,
            R.drawable.ic_fas_step_backward,
            R.drawable.ic_fas_step_forward,
            R.drawable.ic_fas_stethoscope,
            R.drawable.ic_fas_sticky_note,
            R.drawable.ic_fas_stop,
            R.drawable.ic_fas_stop_circle,
            R.drawable.ic_fas_stopwatch,
            R.drawable.ic_fas_street_view,
            R.drawable.ic_fas_strikethrough,
            R.drawable.ic_fas_subscript,
            R.drawable.ic_fas_subway,
            R.drawable.ic_fas_suitcase,
            R.drawable.ic_fas_sun,
            R.drawable.ic_fas_superscript,
            R.drawable.ic_fas_sync,
            R.drawable.ic_fas_sync_alt,
            R.drawable.ic_fas_table,
            R.drawable.ic_fas_tablet,
            R.drawable.ic_fas_tablet_alt,
            R.drawable.ic_fas_tachometer_alt,
            R.drawable.ic_fas_tag,
            R.drawable.ic_fas_tags,
            R.drawable.ic_fas_tasks,
            R.drawable.ic_fas_taxi,
            R.drawable.ic_fas_terminal,
            R.drawable.ic_fas_text_height,
            R.drawable.ic_fas_text_width,
            R.drawable.ic_fas_th,
            R.drawable.ic_fas_th_large,
            R.drawable.ic_fas_th_list,
            R.drawable.ic_fas_thermometer_empty,
            R.drawable.ic_fas_thermometer_full,
            R.drawable.ic_fas_thermometer_half,
            R.drawable.ic_fas_thermometer_quarter,
            R.drawable.ic_fas_thermometer_three_quarters,
            R.drawable.ic_fas_thumbs_down,
            R.drawable.ic_fas_thumbs_up,
            R.drawable.ic_fas_thumbtack,
            R.drawable.ic_fas_ticket_alt,
            R.drawable.ic_fas_times,
            R.drawable.ic_fas_times_circle,
            R.drawable.ic_fas_tint,
            R.drawable.ic_fas_toggle_off,
            R.drawable.ic_fas_toggle_on,
            R.drawable.ic_fas_trademark,
            R.drawable.ic_fas_train,
            R.drawable.ic_fas_transgender,
            R.drawable.ic_fas_transgender_alt,
            R.drawable.ic_fas_trash,
            R.drawable.ic_fas_trash_alt,
            R.drawable.ic_fas_tree,
            R.drawable.ic_fas_trophy,
            R.drawable.ic_fas_truck,
            R.drawable.ic_fas_tty,
            R.drawable.ic_fas_tv,
            R.drawable.ic_fas_umbrella,
            R.drawable.ic_fas_underline,
            R.drawable.ic_fas_undo,
            R.drawable.ic_fas_undo_alt,
            R.drawable.ic_fas_universal_access,
            R.drawable.ic_fas_university,
            R.drawable.ic_fas_unlink,
            R.drawable.ic_fas_unlock,
            R.drawable.ic_fas_unlock_alt,
            R.drawable.ic_fas_upload,
            R.drawable.ic_fas_user,
            R.drawable.ic_fas_user_circle,
            R.drawable.ic_fas_user_md,
            R.drawable.ic_fas_user_plus,
            R.drawable.ic_fas_user_secret,
            R.drawable.ic_fas_user_times,
            R.drawable.ic_fas_users,
            R.drawable.ic_fas_utensil_spoon,
            R.drawable.ic_fas_utensils,
            R.drawable.ic_fas_venus,
            R.drawable.ic_fas_venus_double,
            R.drawable.ic_fas_venus_mars,
            R.drawable.ic_fas_video,
            R.drawable.ic_fas_volume_down,
            R.drawable.ic_fas_volume_off,
            R.drawable.ic_fas_volume_up,
            R.drawable.ic_fas_wheelchair,
            R.drawable.ic_fas_wifi,
            R.drawable.ic_fas_window_close,
            R.drawable.ic_fas_window_maximize,
            R.drawable.ic_fas_window_minimize,
            R.drawable.ic_fas_window_restore,
            R.drawable.ic_fas_won_sign,
            R.drawable.ic_fas_wrench,
            R.drawable.ic_fas_yen_sign,
    )
}